spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
  profiles:
    active: local

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
