name: ecocycle-backend-CI

on:
  pull_request:
    branches:
      - main
    paths:
      - Backend/**
    types: [ opened, synchronize ]

defaults:
  run:
    working-directory: Backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: Change gradlew permission
        run: sudo chmod 755 gradlew

      - name: Build with Gradle
        run: ./gradlew build
